# Copyright (c) 2026, Nimbix, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are
# those of the authors and should not be interpreted as representing official
# policies, either expressed or implied, of Nimbix, Inc.

# OpenFOAM Foundation, inc -> org
# OpenCFD Ltd -> com

# Openfoam Version
ARG OPENFOAM_VERSION=11
ARG OPENFOAM_TYPE=ORG

# Serial Number
ARG SERIAL_NUMBER=20240117.1000

FROM us-docker.pkg.dev/jarvice/images/mpi-builder:5.0.10-el9-gcc15 AS buffer

# Update SERIAL_NUMBER to force rebuild of all layers (don't use cached layers)
ARG SERIAL_NUMBER
ENV SERIAL_NUMBER=${SERIAL_NUMBER}

ARG OPENFOAM_VERSION
ENV OPENFOAM_VERSION=${OPENFOAM_VERSION}

ARG OPENFOAM_TYPE
ENV OPENFOAM_TYPE=${OPENFOAM_TYPE}

# Enable fast mirrors
RUN echo "max_parallel_downloads=20" >> /etc/dnf/dnf.conf && \
    echo "fastestmirror=True" >> /etc/dnf/dnf.conf && \
    dnf update -y --refresh

# Add dependencies
RUN dnf install -y epel-release
RUN dnf config-manager --set-enabled crb
RUN dnf update -y
RUN dnf install -y\
    bc\
    cmake\
    diffutils\
    fftw-devel\
    flex\
    gcc-c++\
    gmp-devel\
    libffi-devel\
    m4\
    mousepad\
    mpfr-devel\
    openssh-clients\
    paraview\
    perl\
    wget\
    which\
    zlib-devel

# Add OpenFOAM Repo (-4 -> use ipv4 -nv -> no verbose)
WORKDIR /opt/OpenFOAM
RUN curl -L http://dl.openfoam.org/source/${OPENFOAM_VERSION} | tar xz
RUN curl -L http://dl.openfoam.org/third-party/${OPENFOAM_VERSION} | tar xz
RUN mv OpenFOAM-${OPENFOAM_VERSION}-version-${OPENFOAM_VERSION} OpenFOAM-${OPENFOAM_VERSION}
RUN mv ThirdParty-${OPENFOAM_VERSION}-version-${OPENFOAM_VERSION} ThirdParty-${OPENFOAM_VERSION}

# Add missing ThirdParty source
WORKDIR /opt/OpenFOAM/ThirdParty-${OPENFOAM_VERSION}
RUN curl -L https://karypis.github.io/glaros/files/sw/metis/metis-5.1.0.tar.gz | tar xz
RUN curl -L https://karypis.github.io/glaros/files/sw/parmetis/parmetis-4.0.3.tar.gz | tar xz

# Update package settings
RUN sed -i s",ParaView_TYPE=system,ParaView_TYPE=none," /opt/OpenFOAM/OpenFOAM-${OPENFOAM_VERSION}/etc/bashrc &&\
    sed -i s",METIS_TYPE=none,METIS_TYPE=ThirdParty," /opt/OpenFOAM/OpenFOAM-${OPENFOAM_VERSION}/etc/bashrc &&\
    sed -i s",--with-mpi=\$MPI_ARCH_PATH,--with-mpi=/opt/JARVICE-MPI/openmpi," /opt/OpenFOAM/ThirdParty-${OPENFOAM_VERSION}/Allwmake &&\
    sed -i s",--with-mpi-libdir=\$MPI_ARCH_PATH/lib\${WM_COMPILER_LIB_ARCH},--with-mpi-libdir=/opt/JARVICE-MPI/openmpi/lib," /opt/OpenFOAM/ThirdParty-${OPENFOAM_VERSION}/Allwmake

SHELL ["/bin/bash", "-c"]
RUN source /opt/JARVICE-MPI/jarvice_mpi.sh && \
    source /opt/OpenFOAM/OpenFOAM-${OPENFOAM_VERSION}/etc/bashrc && \
    cd /opt/OpenFOAM/ThirdParty-${OPENFOAM_VERSION} && \
    ./Allwmake -j$(nproc) -q

RUN source /opt/JARVICE-MPI/jarvice_mpi.sh && \
    source /opt/OpenFOAM/OpenFOAM-${OPENFOAM_VERSION}/etc/bashrc && \
    cd /opt/OpenFOAM/OpenFOAM-${OPENFOAM_VERSION} && \
    ./Allwmake -j$(nproc) -q && \
    ./Allwmake -j$(nproc) -q && rm -rf build

# Main Program
FROM us-docker.pkg.dev/jarvice/images/mpi-builder:5.0.10-el9-gcc15
LABEL maintainer="Nimbix, Inc." \
      license="BSD"

# Update SERIAL_NUMBER to force rebuild of all layers (don't use cached layers)
ARG SERIAL_NUMBER
ENV SERIAL_NUMBER=${SERIAL_NUMBER}

ARG OPENFOAM_VERSION
ENV OPENFOAM_VERSION=${OPENFOAM_VERSION}

ARG OPENFOAM_TYPE
ENV OPENFOAM_TYPE=${OPENFOAM_TYPE}

RUN echo "max_parallel_downloads=20" >> /etc/dnf/dnf.conf
RUN echo "fastestmirror=True" >> /etc/dnf/dnf.conf
RUN dnf update -y --refresh

WORKDIR /tmp

# Install image-common tools and desktop
RUN dnf install -y epel-release
RUN dnf config-manager --set-enabled crb
RUN dnf update -y && \
    dnf install -y ca-certificates && \
    curl -H 'Cache-Control: no-cache' \
        https://raw.githubusercontent.com/nimbix/jarvice-desktop/master/install-nimbix.sh \
        | bash

RUN dnf install -y\
    bc\
    cmake\
    diffutils\
    fftw\
    flex\
    gcc-c++\
    gmp\
    htop btop\
    libffi\
    m4\
    mousepad\
    mpfr\
    openssh-clients\
    paraview\
    perl\
    wget\
    which\
    zlib

# Copy over files
COPY --from=buffer --chmod=0777 /opt/OpenFOAM/OpenFOAM-${OPENFOAM_VERSION} /opt/OpenFOAM/OpenFOAM-${OPENFOAM_VERSION}
COPY --from=buffer --chmod=0777 /opt/OpenFOAM/ThirdParty-${OPENFOAM_VERSION}/platforms /opt/OpenFOAM/ThirdParty-${OPENFOAM_VERSION}/platforms

# Replace custom foamJob file with one provided by openfoam
COPY buildScripts/foamJob.com /opt/OpenFOAM/OpenFOAM-${OPENFOAM_VERSION}/bin/foamJob

COPY scripts /usr/local/scripts

RUN echo "OPENFOAM_VERSION=${OPENFOAM_VERSION}" >> /etc/environment
RUN echo "OPENFOAM_TYPE=${OPENFOAM_TYPE}" >> /etc/environment

COPY NAE/screenshot.png /etc/NAE/screenshot.png
COPY NAE/license.txt /etc/NAE/license.txt
COPY NAE/OpenFOAM-logo-135x135.png /etc/NAE/OpenFOAM-logo-135x135.png

RUN echo "" >> /etc/NAE/license.txt && cat /opt/OpenFOAM/OpenFOAM-${OPENFOAM_VERSION}/COPYING >> /etc/NAE/license.txt

# Copy over the app image and the AppDef
COPY NAE/AppDef-org.json /etc/NAE/AppDef.json
RUN curl --fail -X POST -d @/etc/NAE/AppDef.json https://cloud.nimbix.net/api/jarvice/validate
RUN mkdir -p /etc/NAE && touch /etc/NAE/{screenshot.png,screenshot.txt,license.txt,AppDef.json,swlicense.txt}
